# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Fat Controller / Fat Model の検出
Metrics/ClassLength:
  Enabled: true
  Max: 100

Metrics/MethodLength:
  Enabled: true
  Max: 15

Metrics/AbcSize:
  Enabled: true
  Max: 17

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 7
